### PR TITLE
add swap link

### PR DESCRIPTION
**Pull request by leon-do**
Screenshot 2024-07-27 at 11 56 23 AM

### CODE REVIEW

**Comment by leon-do** [comment]
Screenshot 2024-07-30 at 2 48 34 PM

**Comment by chris-mercer** [comment]
Will you add to the token specific page as well?

Can make address0 in the link just `ETC` and Address1 = the token address.
image

**Comment by leon-do** [comment]
> Will you add to the token specific page as well?
> 
> Can make address0 in the link just `ETC` and Address1 = the token address. image

done

**Comment by chris-mercer** [comment]
"outputCurrency=undefined"

in the link

**Pull request merged**
